name: Continuous integration
on:
  pull_request:
  workflow_call:
  push:
    branches: ['main'] # ['**']
    tags: [v*]
jobs:
  integration-tests:
    name: Check formatting, build and test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest # x86_64-linux
          - macos-latest # aarch64-darwin
          #- macos-13      # x86_64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
          key: ${{ matrix.os }}-bazel-ci-cache
      - name: Format check
        run: |
          bazel run //tools/format:format.check
      - name: Build server
        run: |
          bazel build //server/...
      - name: Run tests
        run: |
          bazel test //server/...
      - name: Run e2e tests
        run: |
          bazel test //server/e2e:all_tests --test_tag_filters=-ci-disabled
