name: Publish jar
on:
  release:
    types: [created]
    branches: [main, temporary-main]
jobs:
  tests:
    uses: ./.github/workflows/ci.yaml
  publish:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
          key: ubuntu-latest-bazel-ci-cache
      - name: Publish package
        run: |
          bazel run \
            --define signing_key=${PGP_SECRET} \
            --define signing_passwd=${PGP_PASSPHRASE} \
            --define sonatype_token=$(printf $SONATYPE_USERNAME:$SONATYPE_PASSWORD | base64 -w0) \
            //server/install:publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: $${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: $${{ secrets.PGP_SECRET }}

