name: Publish jar
on:
  release:
    types: [created]
    branches: [main, temporary-main]
jobs:
  tests:
    uses: ./.github/workflows/ci.yaml
  publish:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
          key: ubuntu-latest-bazel-ci-cache
      - name: Publish package
        run: |
          bazel run \
            //server/install:publish \
            --action_env=SONATYPE_USERNAME \
            --action_env=SONATYPE_PASSWORD \
            --action_env=SONATYPE_SIGNING_KEY \
            --action_env=SONATYPE_SIGNING_KEY_PASSWORD
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_SIGNING_KEY: ${{ secrets.PGP_SECRET }}
          SONATYPE_SIGNING_KEY_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}
